In [1]:
import numpy as np 

def func(x):
    return np.exp(x)*x-x*x-1

def dfunc(x):
    return np.exp(x)*(x+1)-2*x

def express_func(x):
    return np.log((1+x*x)/x)

def simple_iter(func,a,b,eps,flag):
    q = 0.99
    x = (a+b)/2
    count = 0
    ans = []
    while(True):
        ans.append([count, x, func(x)])
        x0 = x
        x = func(x)
        count+=1
        if (q/(1-q)*np.abs(x-x0)<eps) or (count>100):
            break
    if flag == True:
        return np.array(ans)
    else:
        return np.array(ans[-1])


def newton(func,dfunc,x0,eps,flag):
    x = x0
    count = 0
    ans = []
    while True:
        ans.append([count, x, func(x)/dfunc(x)])
        x0 = x
        x -= func(x)/dfunc(x)
        count+=1
        if (np.abs(x-x0)<eps) or (count>100):
            break
    if flag == True:
        return np.array(ans)
    else:
        return np.array(ans[-1])
        
print("Метод простых итераций:")
print(simple_iter(express_func,0.6,0.8,0.001, True))
print("Метод Ньютона:")
print(newton(func,dfunc,0.8,0.001,True))            

Метод простых итераций:
[[ 0.          0.7         0.75545106]
 [ 1.          0.75545106  0.73196567]
 [ 2.          0.73196567  0.74105599]
 [ 3.          0.74105599  0.73739452]
 [ 4.          0.73739452  0.73884719]
 [ 5.          0.73884719  0.7382673 ]
 [ 6.          0.7382673   0.73849822]
 [ 7.          0.73849822  0.73840618]
 [ 8.          0.73840618  0.73844285]
 [ 9.          0.73844285  0.73842824]
 [10.          0.73842824  0.73843406]]
Метод Ньютона:
[[0.00000000e+00 8.00000000e-01 5.83683622e-02]
 [1.00000000e+00 7.41631638e-01 3.19041210e-03]
 [2.00000000e+00 7.38441226e-01 8.82488493e-06]]


Метод простых итераций:
[[ 0.          0.7         0.75545106]
 [ 1.          0.75545106  0.73196567]
 [ 2.          0.73196567  0.74105599]
 [ 3.          0.74105599  0.73739452]
 [ 4.          0.73739452  0.73884719]
 [ 5.          0.73884719  0.7382673 ]
 [ 6.          0.7382673   0.73849822]
 [ 7.          0.73849822  0.73840618]
 [ 8.          0.73840618  0.73844285]
 [ 9.          0.73844285  0.73842824]
 [10.          0.73842824  0.73843406]]
Метод Ньютона:
[[0.00000000e+00 8.00000000e-01 5.83683622e-02]
 [1.00000000e+00 7.41631638e-01 3.19041210e-03]
 [2.00000000e+00 7.38441226e-01 8.82488493e-06]]
